globals:
  seed: 1
  device: cuda
  num_epochs: 60

data:
  data_dir: PUT PATH TO COCO2017
  input_size: 368
  min_keypoints: 5
  min_area: 1024
  paf_sigma: 8
  heatmap_sigma: 7
  min_box_size: 64
  max_box_size: 512
  min_scale: 0.5
  max_scale: 2.0
  max_rotate_degree: 40
  center_perterb_max: 40
  stride: 8
  image_tool: cv2
  input_mode: RGB
  include_val: False

loader:
  train:
    batch_size: 6
    shuffle: False
    pin_memory: True
    num_workers: 16
  val:
    batch_size: 6
    shuffle: False
    pin_memory: False
    num_workers: 16

model:
  name: OpenPose
  backbone: vgg19
  pretrained: true
  params: null

criterion:
  name: Custom_Loss
  loss_weights:
    heatmap_loss0: 1.0
    heatmap_loss1: 1.0
    heatmap_loss2: 1.0
    heatmap_loss3: 1.0
    heatmap_loss4: 1.0
    heatmap_loss5: 1.0
    paf_loss0: 1.0
    paf_loss1: 1.0
    paf_loss2: 1.0
    paf_loss3: 1.0
    paf_loss4: 1.0
    paf_loss5: 1.0

optimizer:
  name: Adam
  params:
    lr: 0.0001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 20

runner:
  name: OpenPoseRunner

callbacks:
  - name: MeanLossCallback
    params: Null

  - name: CustomTensorBoard
    params:
      log_path: ./logs/try
